library(affy)
library(stringr)
library(ggplot2)
library(reshape2)
library(limma)
#查找注释包
library(devtools)
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
options(BioC_mirror="https://mirrors.tuna.tsinghua.edu.cn/bioconductor")
#BiocManager::install("GEOquery")
#BiocManager::install("AnnoProbe")
library(GEOquery)
library(AnnoProbe)
checkGPL(GPL = "GPL10558")
checkGPL(GPL = "GPL11154")