options(repos = structure(c(CRAN = "https://mirrors.tuna.tsinghua.edu.cn/CRAN/")))
if (!requireNamespace("BiocManager", quietly = TRUE))
install.packages("BiocManager")
BiocManager::install("GEOquery")
BiocManager::install("limma")
BiocManager::install("affy")
BiocManager::install("clusterProfiler")
options("repos" = c(CRAN="https://mirrors.ustc.edu.cn/CRAN/"))
options(BioC_mirror="https://mirrors.ustc.edu.cn/bioc/")
BiocManager:: install ("org.Hs.eg.db")
library("clusterProfiler")
install.packages("ggplot2")
if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
options(BioC_mirror="https://mirrors.tuna.tsinghua.edu.cn/bioconductor")
BiocManager::install("zlibbioc")
BiocManager::install("GO.db")
install.packages("glmnet")

install.packages("installr")
install.packages("stringr")    ###依赖包
library(stringr)
library(installr)
BiocManager::install("sva")
install.packages("glmnet", dependencies=TRUE)


library(limma)
library(sva)
library(glmnet)
library("clusterProfiler")
